import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {sampleEntries,sampleReport,colors,type Entry} from './sample';
import './style.css';

const token=import.meta.env.MODE==='sample'?'':new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('clearspace-session')||'';
if(token){sessionStorage.setItem('clearspace-session',token);history.replaceState(null,'',location.pathname)}
const native=Boolean(token)&&import.meta.env.MODE!=='sample';
const emptyReport={status:'loading',items:0,roots:[],allocated:'0',logical:'0',reviewable:'0',shared:'0',categories:{},gaps:0};
function bytes(n:string|null|undefined){if(n==null)return 'Unknown';const b=BigInt(n),abs=b<0n?-b:b;const units:[bigint,string][]=[[1024n**3n,'GiB'],[1024n**2n,'MiB'],[1024n,'KiB'],[1n,'B']];const [d,u]=units.find(([d])=>abs>=d)||units[3];return `${Number((abs*100n+d/2n)/d)/100*(b<0n?-1:1)} ${u}`}
function exact(n:string|null|undefined){return n==null?'Unknown':`${BigInt(n).toLocaleString()} bytes`}
async function api(path:string,body?:unknown){const r=await fetch(`/api/${path}`,{method:body===undefined?'GET':'POST',headers:{'X-Clearspace-Token':token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok){const e=await r.json();throw Error(typeof e.detail==='string'?e.detail:'Check the selected items and try again')}return r.json()}
const guidance:Record<string,{title:string,text:string,url:string}>={coverage:{title:'Coverage gap · measurement unavailable',text:'Clearspace could not measure this location. It may be restricted, unavailable or changed during the scan. Leave it unchanged; choose an accessible folder and rescan if needed. This is not evidence of cloud storage or removable space.',url:'https://support.microsoft.com/en-us/windows/experience/storage-filemanagement/manage-drive-space-with-storage-sense'},cloud:{title:'OneDrive · Free up space',text:'Online-only retains the cloud copy. Deleting a synced item can remove it across devices. Opening or moving online-only content can download it. Review the provider’s own controls.',url:'https://support.microsoft.com/en-us/onedrive/save-disk-space-with-onedrive-files-on-demand-for-windows'},storage:{title:'Windows · Storage settings',text:'Storage Sense manages the system drive. For other drives, inspect Advanced storage settings → Storage used on other drives. Review categories and exclusions first.',url:'https://support.microsoft.com/en-us/windows/experience/storage-filemanagement/manage-drive-space-with-storage-sense'},apps:{title:'Windows · Installed apps',text:'Use the owning application’s retention, cache or uninstall controls. Do not remove application databases or package stores based on age or size.',url:'https://learn.microsoft.com/en-us/windows/apps/develop/launch/launch-settings'},review:{title:'Your review comes first',text:'A candidate is a starting point for a decision. Confirm ownership, backups and purpose. Moving into the same-volume Recycle Bin normally retains disk allocation; a move to another drive shifts usage.',url:'https://support.microsoft.com/en-us/windows/experience/storage-filemanagement/manage-drive-space-with-storage-sense'}};

function App(){
 const [sample,setSample]=useState(!native),[report,setReport]=useState<any>(native?emptyReport:sampleReport(sampleEntries)),[entries,setEntries]=useState<Entry[]>(native?[]:sampleEntries),[selected,setSelected]=useState<Entry|null>(native?null:sampleEntries[0]),[config,setConfig]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[scope,setScope]=useState(''),[protectedPaths,setProtectedPaths]=useState(''),[showScope,setShowScope]=useState(native),[category,setCategory]=useState(''),[sort,setSort]=useState('allocated'),[direction,setDirection]=useState('desc'),[page,setPage]=useState(0),[total,setTotal]=useState(native?0:8),[checks,setChecks]=useState<number[]>([]),[dupes,setDupes]=useState<any>(null),[busy,setBusy]=useState(false);
 const [picker,setPicker]=useState<any>({status:'idle'});
 const picking=['pending','open'].includes(picker.status);
 const [folder,setFolder]=useState(''),[folderPage,setFolderPage]=useState(0),[tree,setTree]=useState<any>({entries:[]}),[folderLoading,setFolderLoading]=useState(false);
 const folderFocus=useRef(false),detailFocus=useRef(false);
 const perform=async(fn:()=>Promise<void>)=>{setError('');setMessage('');setBusy(true);try{await fn()}catch(e){setMessage('');setError(String(e instanceof Error?e.message:e))}finally{setBusy(false)}};
 async function refresh(){const [r,e,d]=await Promise.all([api('report'),api(`entries?offset=${page*50}&sort=${sort}&direction=${direction}${category?`&category=${encodeURIComponent(category)}`:''}`),api('duplicates')]);setReport(r);setEntries(e.entries);setTotal(e.total);setDupes(d);setSelected(s=>s?e.entries.find((x:Entry)=>x.id===s.id)||s:null)}
 useEffect(()=>{if(native){api('config').then(setConfig).catch(e=>setError(e.message));api('pick').then(setPicker).catch(e=>setError(e.message))}},[]);
 useEffect(()=>{if(!picking)return;let active=true;const poll=async()=>{try{const p=await api('pick');if(!active)return;setPicker(p);if(p.status==='selected'){setScope(s=>[...new Set([...s.split('\n').filter(Boolean),p.path])].join('\n'));setMessage('Folder selected. Review the path, then start the scan.')}else if(p.status==='cancelled')setMessage('Folder selection cancelled. You can browse again or paste a path.');else if(p.status==='error')setError(p.message)}catch(e){if(active){setPicker({status:'error'});setError('The picker connection was lost. Cancel any open Windows dialog, then paste a path or retry.')}}};const id=setInterval(()=>void poll(),600);return()=>{active=false;clearInterval(id)}},[picking]);
 useEffect(()=>{if(sample)return;let active=true;setFolderLoading(true);setTree({entries:[]});api(`browse?path=${encodeURIComponent(folder)}&offset=${folderPage*50}`).then(t=>{if(active){setTree(t);setFolderLoading(false)}}).catch(e=>{if(active){setError(e.message);setFolderLoading(false)}});return()=>{active=false}},[sample,folder,folderPage,report.items,report.scan_id]);
 useEffect(()=>{if(!folderLoading&&folderFocus.current){folderFocus.current=false;document.getElementById('folder-heading')?.focus()}},[tree,folderLoading]);
 useEffect(()=>{if(selected&&detailFocus.current){detailFocus.current=false;const panel=document.getElementById('review-details');panel?.focus();panel?.scrollIntoView({behavior:'instant',block:'center'})}},[selected]);
 function selectEntry(entry:Entry){detailFocus.current=true;setSelected({...entry})}
 async function browse(){setError('');setMessage('');setPicker({status:'pending'});try{setPicker(await api('pick',{}))}catch(e){setPicker({status:'error'});setError(e instanceof Error?e.message:String(e))}}
 function navigate(path:string){if(path===folder&&folderPage===0)return;folderFocus.current=true;setTree({entries:[]});setFolderLoading(true);setFolder(path);setFolderPage(0)}
 useEffect(()=>{if(sample)return;void perform(refresh);const id=setInterval(()=>{void refresh().catch(e=>setError(e.message))},1500);return()=>clearInterval(id)},[sample,page,sort,direction,category]);
 useEffect(()=>{if(!sample){setSelected(null);setChecks([])}},[report.scan_id]);
 const list=sample?[...entries].filter(e=>!category||e.category===category).sort((a,b)=>{const x=sort==='path'?a.path:BigInt((a as any)[sort]||'-1'),y=sort==='path'?b.path:BigInt((b as any)[sort]||'-1');return (x<y?-1:x>y?1:0)*(direction==='asc'?1:-1)}):entries;
 const scanning=report.status==='scanning'||dupes?.status==='reading';
 const totalAllocated=BigInt(report.allocated||'0');
 const map=Object.entries(report.categories||{}).filter(([,n])=>BigInt(String(n))>0);
 async function mark(value:string){if(!selected)return;if(sample){const next=entries.map(e=>e.id===selected.id?{...e,mark:value}:e);setEntries(next);setReport(sampleReport(next));setSelected({...selected,mark:value});setMessage('Sample review choice saved for this visit.')}else{await api('mark',{id:selected.id,scan_id:report.scan_id,value});setSelected({...selected,mark:value});await refresh();setMessage('Review choice saved. Keep choices persist across rescans.')}}
 async function start(){const previous=report;setReport({...report,status:'starting'});setMessage('Starting metadata scan…');try{await api('scan',{roots:scope.split('\n').map(x=>x.trim()).filter(Boolean),protected:protectedPaths.split('\n').map(x=>x.trim()).filter(Boolean)})}catch(e){setReport(previous);throw e}setTree({entries:[]});setEntries([]);setSample(false);navigate('');setMessage('Scan started. Items will appear as they are measured.');setSelected(null);setPage(0);setCategory('');setChecks([]);setShowScope(false);await refresh()}
 async function exportPlan(){let blob:Blob;if(sample)blob=new Blob([JSON.stringify({fictional:true,report,entries},null,2)],{type:'application/json'});else{const r=await fetch('/api/export',{headers:{'X-Clearspace-Token':token}});if(!r.ok)throw Error('Finish the active operation before exporting');blob=await r.blob()}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=sample?'Clearspace-fictional-plan.json':'Clearspace-private-plan.ndjson';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(sample?'Fictional plan exported.':'Plan exported with private local paths. Review before sharing.')}
 return <div className="app"><header><a className="brand" href="#top"><span className="brand-mark">▥</span> clearspace<span className="preview">PREVIEW</span></a><div className="header-right"><span className="local-dot"/> {native?'Local session · no model':'Interactive sample · no model'}<a href="https://github.com/mastodonsharkgirl/clearspace/releases" target="_blank" rel="noreferrer">Windows download ↗</a></div></header>
 <main id="top"><div className="hero"><div><p className="eyebrow">A LITTLE CLARITY. A LOT MORE ROOM.</p><h1>Your space,<br/><em>understood.</em></h1><p className="intro">Find what’s taking up room. Understand the trade-off.<br/>Choose what goes, on your terms.</p></div><div className="hero-side"><span className="mode-label">{sample?'FICTIONAL DISK / EXPLORER':'YOUR DEVICE / READ-ONLY'}</span><p>{sample?'Explore a small sample before looking at your own files. Nothing on your device is being scanned.':'Metadata stays on this device. Clearspace never deletes or moves your files.'}</p><button className="primary" onClick={()=>native?(setSample(false),setShowScope(true)):setMessage('To scan a local folder, download the Windows preview, extract the ZIP and open Clearspace.exe.')}>{native?'Choose a folder':'How to scan my own files'} <span>↗</span></button>{!sample&&<button className="text-button" onClick={()=>{setSample(true);setEntries(sampleEntries);setReport(sampleReport(sampleEntries));setSelected(sampleEntries[0]);setCategory('');setChecks([]);setDupes(null)}}>Explore fictional sample</button>}</div></div>
 {showScope&&<section className="scope panel"><h2>Choose exactly what to scan</h2><p>Metadata only. Links, cloud placeholders and named NTFS streams are excluded. No files are changed.</p><label>Local folder or drive roots · one per line<textarea aria-label="Local folder or drive roots · one per line" value={scope} onChange={e=>setScope(e.target.value)} placeholder="C:\\Users\\You\\Downloads"/></label><div className="scope-actions">{config?.picker&&<button disabled={picking} onClick={()=>void browse()}>{picking?'Waiting for Windows picker…':'Browse for a folder'}</button>}{(config?.drives||[]).map((drive:string)=><button key={drive} aria-label={`Select drive ${drive}`} onClick={()=>setScope(s=>[...new Set([...s.split('\n').filter(Boolean),drive])].join('\n'))}>{drive}</button>)}</div>{picking&&<p role="status">Windows folder picker is open. Choose a folder, or use Cancel in that window. If hidden, select the Clearspace launcher in the taskbar. You can also paste a path below.</p>}<p className="small">Paste a full folder path from File Explorer, or select a drive above. Selecting a path does not scan it until you press Start.</p><label>Protected folders · optional, one per line<textarea value={protectedPaths} onChange={e=>setProtectedPaths(e.target.value)}/></label><p className="small">Inventory: <code>{config?.data_location}</code><br/>Available: {bytes(config?.available)} · Inventory budget: {bytes(config?.budget)} · Free-space reserve: {bytes(config?.reserve)}. Change the data location in the launcher before starting.</p><button className="primary" disabled={busy||scanning||!scope.trim()} onClick={()=>void perform(start)}>Start metadata scan</button><button onClick={()=>setShowScope(false)}>Close</button></section>}
 <div className="notice" role="status"><span className="notice-icon">{sample?'◈':'◎'}</span><div><strong>{sample?'Fictional sample':'Local inventory'} · {report.status==='complete'?'Selected scope enumerated':report.status==='scanning'?'Scanning metadata':report.status==='starting'?'Starting metadata scan':report.status==='loading'?'Loading saved inventory':report.status==='empty'?'Choose a folder to begin':report.status==='cancelled'?'Scan cancelled · partial results':'Partial coverage'}</strong><span>{report.reason||`${report.items} items scanned so far. ${report.gaps||0} coverage gaps.`} {report.status==='scanning'&&'The total is unknown; no percentage is estimated.'}</span></div>{scanning&&<button onClick={()=>void perform(async()=>{await api('cancel',{});setMessage('Cancellation requested; committed results will remain available.')})}>Cancel operation</button>}</div>
 {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="message" role="status">{message}</div>}
 <section className="metrics" aria-label="Inventory measurements"><div><p>Known local allocation</p><strong title={exact(report.allocated)}>{bytes(report.allocated)}</strong><span>File default streams · hard links counted once</span></div><div><p>Logical file length</p><strong title={exact(report.logical)}>{bytes(report.logical)}</strong><span>Each discovered file name · not disk usage</span></div><div><p>Reviewable allocation</p><strong title={exact(report.reviewable)}>{bytes(report.reviewable)}</strong><span>Excludes Keep, protected and shared links</span></div><div className="uncertainty"><p>Potential recovery</p><strong>Not estimated</strong><span>Reviewable does not mean safe to remove</span></div></section>
 <div className="workspace"><section className="panel map-panel"><div className="section-head"><div><p className="eyebrow">01 / SEE THE SPACE</p><h2>A map of what we know</h2></div><span className="pill">{report.items} items</span></div><p className="small">Area = known default-stream allocation. Select a category to filter the table.</p><div className="treemap" role="group" aria-label="Allocation map">{map.length?map.map(([name,value],index)=><button key={name} style={{width:`${Number(BigInt(String(value))*100000n/(totalAllocated||1n))/1000}%`,left:`${Number(map.slice(0,index).reduce((s,[,v])=>s+BigInt(String(v)),0n)*100000n/(totalAllocated||1n))/1000}%`,background:colors[name]||'#bbb'}} onClick={()=>{setCategory(category===name?'':name);setPage(0)}} aria-pressed={category===name}><strong>{name}</strong><span>{bytes(String(value))}</span></button>):<p>No measured allocation yet. Unknown measurements remain visible in the table.</p>}</div><div className="legend">{Object.entries(colors).map(([name,color])=><button key={name} onClick={()=>{setCategory(category===name?'':name);setPage(0)}} aria-pressed={category===name}><i style={{background:color}}/>{name}</button>)}</div><div className="map-foot"><span>{report.unknown_allocation||0} file allocations unknown</span><span>{bytes(report.shared)} shared hard-link allocation</span><span>{report.gaps||0} coverage gaps</span></div></section>
 <section className="panel volume-panel"><p className="eyebrow">THE BIGGER PICTURE</p><h2>Volume context</h2>{(report.before||[]).map((v:any)=>{const rest=BigInt(v.total)-BigInt(v.free)-totalAllocated;const after=(report.after||[]).find((x:any)=>x.volume===v.volume);return <div className="volume" key={v.volume}><h3>{v.root}</h3><div className="volume-bar"><span style={{width:`${Number((BigInt(v.total)-BigInt(v.free))*100n/BigInt(v.total))}%`}}/></div><dl><dt>Free on volume</dt><dd title={exact(v.free)}>{bytes(v.free)}</dd><dt>Available to caller</dt><dd title={exact(v.available)}>{bytes(v.available)}</dd><dt>Reported capacity*</dt><dd>{bytes(v.total)}</dd></dl><p className="small">{report.before.length===1?`${bytes(String(rest>0n?rest:0n))} system, inaccessible or unaccounted space. Includes everything outside the selected scope.`:'Multiple volumes: explained allocation is aggregated; no per-volume remainder is inferred.'}</p><time>{new Date(v.at).toLocaleString()}</time>{after&&<p className="change">Observed net free-space change: <strong>{bytes(String(BigInt(after.free)-BigInt(v.free)))}</strong><br/><time>{new Date(after.at).toLocaleString()}</time></p>}</div>})}<p className="small">*Capacity available to the caller; quotas can affect it. A net change is an observation, not a claim of app-caused savings.</p><button disabled={scanning||busy} onClick={()=>void perform(async()=>{if(sample){setMessage('Sample only: a fictional +2 GiB net change is shown. No device measurement occurred.');setReport({...report,after:report.before.map((v:any)=>({...v,free:String(BigInt(v.free)+2n*1024n**3n),at:new Date().toISOString()}))})}else{await api('remeasure',{});await refresh()}})}>Re-measure free space ↻</button></section></div>
 {!sample&&<section className="panel folder-panel"><div className="section-head"><div><p className="eyebrow">FOLLOW THE SPACE</p><h2 id="folder-heading" tabIndex={-1}>Folders & files</h2></div><button disabled={!folder||folderLoading} onClick={()=>navigate(tree.parent||'')}>Up one level ↑</button></div><nav aria-label="Folder navigation"><button disabled={folderLoading} onClick={()=>navigate('')}>Scanned roots</button><code>{folder||'Choose a scanned root below'}</code></nav><p role="status">{folderLoading?'Loading folder…':`${tree.entries.length} entries shown`}</p><p className="small">Known allocation beneath each folder, including nested files. Shared hard links count once within each folder and may appear in more than one folder. Unknown or skipped items mean totals can be incomplete.</p><div className="table-scroll"><table><thead><tr><th>Folder / file</th><th>Known allocation</th><th>Files</th><th>Coverage</th></tr></thead><tbody>{tree.entries.map((item:any)=><tr key={item.path}><td><button className="row-button" disabled={!item.navigable&&!item.id} onClick={()=>{if(item.navigable)navigate(item.path);else void perform(async()=>{selectEntry(await api(`entry/${item.id}`))})}}><strong>{folder?item.path.split(/[\\/]/).filter(Boolean).pop():item.path}{item.navigable?' ↗':''}</strong><span>{item.kind}</span></button></td><td title={exact(item.allocated)}>{bytes(item.allocated)}</td><td>{item.files}</td><td>{item.gaps||item.unknown?`${item.gaps} skipped · ${item.unknown} unknown`:'Known so far'}</td></tr>)}</tbody></table>{!folderLoading&&!tree.entries.length&&<p className="empty">{folderLoading?'Loading folder…':report.status==='empty'?'Choose a folder or drive above to see your actual files here.':scanning?'Waiting for the first recorded items…':'No recorded children in this folder.'}</p>}</div><div className="pagination"><button disabled={!folderPage||folderLoading} onClick={()=>setFolderPage(p=>p-1)}>Previous folders</button><span>Page {folderPage+1}</span><button disabled={!tree.has_more||folderLoading} onClick={()=>setFolderPage(p=>p+1)}>Next folders</button></div></section>}
 <section className="panel review-panel"><div className="section-head"><div><p className="eyebrow">02 / MAKE A PLAN</p><h2>Worth a closer look</h2></div><button disabled={scanning||busy} onClick={()=>void perform(exportPlan)}>Export review plan ↓</button></div><p className="small">Select a row to inspect its reason and exact location. Your operating system handles any changes.</p><div className="toolbar"><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">All categories</option>{Object.keys(colors).map(x=><option key={x}>{x}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="allocated">Local allocation</option><option value="logical">Logical length</option><option value="path">Path</option></select></label><button onClick={()=>setDirection(d=>d==='desc'?'asc':'desc')}>{direction==='desc'?'Descending ↓':'Ascending ↑'}</button><span>{sample?list.length:total} items</span></div>
 <div className="review-grid"><div><div className="table-scroll"><table><thead><tr><th><span className="sr-only">Compare</span></th><th scope="col">Item / location</th><th scope="col">Allocated</th><th scope="col">Review state</th></tr></thead><tbody>{list.map(e=><tr key={e.id} className={selected?.id===e.id?'selected':''}><td><input type="checkbox" aria-label={`Compare ${e.path}`} checked={checks.includes(e.id)} disabled={e.kind!=='file'||e.cloud!=='ordinary-local'||e.links!==1||scanning} onChange={()=>setChecks(c=>c.includes(e.id)?c.filter(x=>x!==e.id):[...c,e.id])}/></td><td><button className="row-button" onClick={()=>selectEntry(e)}><strong>{e.path.split(/[\\/]/).pop()}</strong><span>{e.category}</span></button></td><td title={exact(e.allocated)}>{bytes(e.allocated)}</td><td><span className="state">{e.mark==='keep'?'Keep':e.mark==='later'?'Review later':e.protected?'Protected review':'To review'}</span></td></tr>)}</tbody></table>{!list.length&&<p className="empty">No items in this view. Choose another category or scan a folder.</p>}</div>{!sample&&<div className="pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={(page+1)*50>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}<div className="duplicate-box"><strong>Compare selected main file contents</strong><p>This separate stage reads local file contents, up to 2 GiB per operation. Cloud, reparse and shared-link items are excluded. Named streams are not compared.</p><button disabled={checks.length<2||checks.length>100||scanning||busy} onClick={()=>void perform(async()=>{if(sample){setMessage('Fictional sample: content comparison requires the local Windows app. No file contents were read.')}else{await api('duplicates',{ids:checks,scan_id:report.scan_id});await refresh()}})}>Read and compare {checks.length} selected files</button>{dupes&&<div role="status"><p>Comparison: {dupes.status} · {dupes.groups?.length||0} identical-main-content groups</p>{dupes.groups?.map((g:any,i:number)=><div key={i}><strong>{g.label}</strong><p>Inventory IDs: {g.ids.join(', ')}. Choose a keeper using Keep in the table. No deletion is performed.</p></div>)}{dupes.skipped?.map((s:any,i:number)=><p key={i}>Item {s.id}: {s.reason}</p>)}<p>{dupes.notice}</p></div>}</div></div>
 <aside id="review-details" tabIndex={-1} className="detail" aria-label="Selected item">{selected?<><span className="pill">{selected.protected?'OWNER / PROTECTED REVIEW':'YOUR DECISION'}</span><h3>{selected.path.split(/[\\/]/).pop()}</h3><code className="path">{selected.path}</code><p>{selected.reason}</p>{selected.error&&<details><summary>Measurement diagnostic</summary><code>{selected.error}</code></details>}<dl><dt>Allocated</dt><dd>{exact(selected.allocated)}</dd><dt>Logical length</dt><dd>{exact(selected.logical)}</dd><dt>Measurement</dt><dd>{selected.allocation_status}</dd><dt>Link names</dt><dd>{selected.links??'Unknown'}</dd><dt>Cloud status</dt><dd>{selected.cloud}</dd></dl>{selected.links>1&&<p className="small">Other names may be outside this scope. Removing one name may recover no space.</p>}<div className="actions"><button disabled={scanning||busy} className={selected.mark==='keep'?'active':''} onClick={()=>void perform(()=>mark('keep'))}>Keep</button><button disabled={scanning||busy} onClick={()=>void perform(()=>mark('later'))}>Review later</button><button disabled={scanning||busy} onClick={()=>void perform(()=>mark('review'))}>Reset</button></div><button className="wide" disabled={scanning||busy||selected.kind==='error'||selected.reparse} onClick={()=>void perform(async()=>{if(sample)setMessage(`Sample handoff: the Windows app would open ${selected.parent}.`);else{await api('open',{id:selected.id,scan_id:report.scan_id});setMessage('Containing folder opened. Make any changes through Windows.')}})}>Open containing folder ↗</button>{['apps','storage'].includes(selected.guidance)&&<button className="wide" onClick={()=>void perform(async()=>{if(sample)setMessage(`Sample handoff: Windows ${selected.guidance==='apps'?'Installed apps':'Storage settings'}.`);else await api('settings',{action:selected.guidance})})}>Open {selected.guidance==='apps'?'Installed apps':'Storage settings'} ↗</button>}<div className="guidance"><p className="eyebrow">WHY THIS GUIDANCE?</p><h4>{guidance[selected.guidance]?.title}</h4><p>{guidance[selected.guidance]?.text}</p><a href={guidance[selected.guidance]?.url} target="_blank" rel="noreferrer">Read official guidance ↗</a><span>Bundled card {selected.guidance}/1 · checked 9 Oct 2026 · source-backed templates, no AI generation.</span></div></>:<p>Select an item to see its details and review actions.</p>}</aside></div></section>
 <section className="closing"><div><p className="eyebrow">03 / CHECK THE CHANGE</p><h2>Review. Act in Windows. Measure again.</h2><p>After any manual cleanup, re-measure free space above. Rescan to refresh the inventory. Background writes and delayed cleanup can affect the result.</p></div>{native&&!sample&&<button onClick={()=>{setScope(report.roots.join('\n'));setProtectedPaths((report.protected||[]).join('\n'));setShowScope(true);window.scrollTo({top:0,behavior:'instant'})}}>Review scope & rescan ↻</button>}</section>
 <footer><span>Clearspace · Find the space. Understand the trade-off.</span><details><summary>About this preview</summary><p>0.1.0-preview.3 · Unsigned Windows x64 preview. No model, telemetry, deletion or paid service. Clean standard-user download/Extract all acceptance remains pending. {report.allocation_scope} Named-stream differences are not examined. Source generated with Codex assistance.</p><p>Source commit: {config?.build?.source_commit||'See release manifest'} · Build/test evidence and checksums are linked on the GitHub release.</p></details></footer></main></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
