export const colors:Record<string,string>={'Downloads to review':'#daba75','Personal media':'#8b9f84','Application managed':'#92a7b8','Development':'#b6a2ba','Cloud / reparse':'#b8c8c2','Protected / unknown':'#c5bbaa'};
export type Entry={id:number,path:string,parent:string,kind:string,logical:string,allocated:string|null,category:string,reason:string,protected:boolean,guidance:string,links:number,cloud:string,reparse:boolean,allocation_status:string,mark:string,error?:string|null,modified_ns?:string,identity?:string};
export const sampleEntries:Entry[]=[
 ['C:\\Sample\\Downloads\\Field-notes-film.zip','Downloads to review',18.4,'A downloaded project archive. Confirm the original and any backup before a manual change.',false,'review',1],
 ['C:\\Sample\\Videos\\Coast documentary.mp4','Personal media',12.8,'Original footage. Review ownership and backup before deciding.',false,'review',1],
 ['C:\\Sample\\AppData\\Studio\\library.db','Application managed',8.2,'Application database. Use the owning application’s retention controls.',true,'apps',1],
 ['C:\\Sample\\Projects\\atlas\\node_modules\\bundle','Development',5.6,'Project dependencies. Check the project and its lockfile first.',true,'review',1],
 ['C:\\Sample\\Windows\\shared-component.bin','Protected / unknown',3.2,'Protected system component with two hard-link names. Removing one name may reclaim nothing.',true,'storage',2],
 ['C:\\Sample\\OneDrive\\Archive.zip','Cloud / reparse',0,'Possible cloud placeholder. No content read. Use OneDrive’s own Free up space command when appropriate; deletion can sync across devices.',true,'cloud',1],
 ['C:\\Sample\\Downloads\\Workshop-recording.mp4','Downloads to review',4.6,'A downloaded recording to review. Size alone does not establish that it is unnecessary.',false,'review',1],
 ['C:\\Sample\\Private folder','Protected / unknown',0,'Access denied in this fictional scan. Its contents are unaccounted for.',true,'review',1],
].map((x,i)=>({id:i+1,path:String(x[0]),parent:String(x[0]).split('\\').slice(0,-1).join('\\'),kind:i===7?'error':'file',logical:String(BigInt(Math.round(Number(x[2])*1024**3))+(i===5?12n*1024n**3n:0n)),allocated:i>=5&&i!==6?null:String(Math.round(Number(x[2])*1024**3)),category:String(x[1]),reason:String(x[3]),protected:Boolean(x[4]),guidance:String(x[5]),links:Number(x[6]),cloud:i===5?'possible-placeholder':'ordinary-local',reparse:i===5,allocation_status:i===5?'excluded':i===7?'unknown':'known-default-stream',mark:'review',error:i===7?'access-denied':null}));
export function sampleReport(entries:Entry[]){
 const categories:Record<string,string>={};for(const e of entries)if(e.allocated)categories[e.category]=String(BigInt(categories[e.category]||'0')+BigInt(e.allocated));
 return {scan_id:'fictional',status:'partial',items:8,gaps:2,started:'2026-10-09T09:30:00Z',finished:'2026-10-09T09:30:04Z',roots:['C:\\Sample'],reason:'One cloud item excluded; one folder inaccessible. This is fictional data.',logical:String(entries.reduce((s,e)=>s+BigInt(e.logical),0n)),allocated:String(entries.reduce((s,e)=>s+BigInt(e.allocated||'0'),0n)),reviewable:String(entries.filter(e=>!e.protected&&e.mark!=='keep').reduce((s,e)=>s+BigInt(e.allocated||'0'),0n)),shared:String(Math.round(3.2*1024**3)),unknown_allocation:1,categories,before:[{volume:'sample-C',root:'C:\\Sample',total:String(256n*1024n**3n),free:String(28n*1024n**3n),available:String(28n*1024n**3n),at:'2026-10-09T09:30:00Z'}],after:[] as any[],allocation_scope:'Known file default-stream allocation only; directory metadata, named streams and NTFS overhead excluded.'};
}
